### ISSUE TITLE
Test first step of workflow

### ISSUE THREAD

**Issue by gcapes** [RoryAtBar/Abaqus_bayesian_matflow#1]
The first part of this workflow is a jobscript 
https://github.com/RoryAtBar/Abaqus_bayesian_matflow/blob/main/surrogate_Abaqus_3_800C_1s-1.txt

Can I get this to run on CSF without errors? That is the first step to developing a task schema in Matflow.

**Comment by RoryAtBar** [comment]
Sorry, just noticed this... It should be possible if the initial delete of sub_script_check in the python script doesn't cause any problems... The files copied run the tasks I expect them to, or does the script need to be developed further so that we have a more elegant solution?
