### ISSUE TITLE
Implement read_odb_into_text_file in matflow

### ISSUE THREAD

**Issue by gcapes** [RoryAtBar/Abaqus_bayesian_matflow#10]
It looks like this reads in an odb file and creates several (5?) new files, so it might be best as several separate tasks
`read_odb_into_text_file = subprocess.run(['abq2022','cae', 'noGUI=read_Force_PEEQ_NT11_barrelling_forcemac.py'])`

**Comment by RoryAtBar** [comment]
Perhaps? Do you mean for the sake of improving code readability?

I can see that it would make the workflow clearer and more logical to the user, however if you call abaqus CAE it has to spend time opening up, checking for a licence, and loading up the model. When the script ends, I believe the application just closes. When the script is actually running, it takes seconds.

If you therefore make this in to 5 steps it may take longer to run or occupy more Abaqus licences, and whether this is worth it will depend on the perceived advantages...

**Comment by gcapes** [comment]
Very happy to be advised on this :) I guess it could equally be thought of as one task which "processes odb file" rather than separate tasks which create one output each.

**Comment by RoryAtBar** [comment]
I think that I would prioritise limiting the number of times Abaqus CAE needs to be opened, and yes I would have "process odb file" as a step. 

The script currently extracts:
 Plastic equivalent strain (PEEQ) through a specfic set of nodes at the final time step, 
Temperature (NT11) through the centre at the final timestep
Displacement of the outer nodes of the sample at the final timestep
Compressive force between the top platen and the sample at each timestep
Compressive force between the bottom platen and the sample at each timestep

Adding any additional outputs in python is fairly involved and won't be easy to specify within matflow, and the most resource intensive part of obtaining the outputs is probably opening up Abaqus CAE. Therefore having each individual output as a separate task is probably not worth the pain...
