### ISSUE TITLE
Refactor `modify_platen_conductance`

### ISSUE THREAD

**Issue by gcapes** [RoryAtBar/Abaqus_bayesian_matflow#13]
@RoryAtBar 
This currently has two parameters, but the second is a two-item list.
```
def modify_platen_conductance(inp_text, platen_conductance):
    new_text = inp_text
    replacement_line = str(platen_conductance[0])+',    0.'
    ...
```

Could you explain what the first item in that list represents? The second is a file. I'm planning to split these into two parameters but want to give them reasonable names.

**Comment by gcapes** [comment]
I made a naming decision :) We can always review all these once the workflow is up and running.

**Comment by RoryAtBar** [comment]
The first item is the value of the conductance (integer), the second is the name of the .odb file (as a string) containing the initial temperature distribution given it was heated and held at a certain temperature with a certain interface conductance.

**Comment by RoryAtBar** [comment]
The reason for having a separate model to find the starting temperatures this is that during the heat up step, the power input needs to be calibrated at each timestep for the temperature at a central thermocouple. The conductance will affect the amount of power required and affect the temperature distribution.

This takes a few hours to set up and run, but can be recycled for models with the same conductance value and different friction values.
