### ISSUE TITLE
Run updated scripts on CSF3

### ISSUE THREAD

**Issue by gcapes** [RoryAtBar/Abaqus_bayesian_matflow#20]
@RoryAtBar has got a new approach for this work.
> 1. I want to change the GP from fitting individual data points to fitting basis functions using scikit-fda
> 2. Randomly separate out training data and validation data and test the fit of the validation data (about 20% of the samples to be used not for conditioning the GP, but for checking that the predicted values fit correctly)
> 3. Automatically check which of four kernels fits best rather than picking the first one that fits at all

- [x] Rory to commit the new scripts to this repo, with instructions on how to run them
- [x] Gerard to run them on CSF3 before attempting to integrate them into a MatFlow workflow
  - [x] Test/fix `Data_set_up.sh`
  - [x] Test/fix `PYMC_GPflow_CSF3sampler_step1.sh`
  - [x] Test/fix `PYMC_GPflow_CSF3sampler_step2.sh`
  - [x] Test/fix `PYMC_GPflow_CSF3sampler_step3.sh`

**Comment by gcapes** [comment]
@RoryAtBar, `PYMC_GPflow_CSF3sampler_step1.sh` is giving the following error. Any ideas on this?
I'm working on the `gp_kernel_tester` branch.
```
ValueError: Dimensions must be equal, but are 6 and 2 for '{{node truediv_2}} = RealDiv[T=DT_DOUBLE](strided_slice_8, truediv_2/softplus_CONSTRUCTED_AT_top_level/forward/IdentityN)' with input shapes: [1,6], [2].
```

**Comment by RoryAtBar** [comment]
Hi Gerard,
This has hopefully been fixed. 
Changed the input dimensions for the compiled functions in the saved tensorflow model to [1, number of input dimensions]

**Comment by gcapes** [comment]
I guess this is the same type of problem (from `PYMC_GPflow_CSF3sampler_step2.sh`?
```
ValueError: operands could not be broadcast together with shapes (6,) (2,)
```

**Comment by RoryAtBar** [comment]
Would you mind sending the whole error message?

**Comment by RoryAtBar** [comment]
I forgot that I copied this script from a version of this workflow that modifies constitutive parameters (of which there were 6). I have now updated this so there are only 2 (friction and conductance)

**Comment by gcapes** [comment]
Thanks! Step2  looks to be running ok now (job array hasn't finished yet but no errors on those which have finished 😄)

**Comment by RoryAtBar** [comment]
Great! Hopefully it would have errored by now

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gcapes** [comment]
The last 5 jobs from the job array are still running...no errors yet, but no output either. I think these need to finish before I can test step3, so this issue is blocked for now.

**Comment by gcapes** [comment]
These seem to be taking way longer than the others in the job array, which is suspicious.

**Comment by RoryAtBar** [comment]
Odd, when these jobs run for this long I get segmentation errors.

**Comment by RoryAtBar** [comment]
Step 3 may still work if you go to the job script and remove the line
`#$ -hold_jid PYMC_GPflow_CSF3sampler_step2.sh `
If any of the chains have completed, you should have files called Idata_chain_{number}.nc it will still find and agglomerate them as it uses the glob module to find them.

**Comment by gcapes** [comment]
These step 2 job array jobs are still running, but without any errors or output. I thought there was a time limit of a week, but they're still showing as running ... very strange.
Nonetheless, I've commented out that line to wait on the previous job and submitted step3. It's queued and waiting.

**Comment by gcapes** [comment]
I've now submitted a support ticket because those jobs have been stalled/waiting for way longer than normal.

**Comment by gcapes** [comment]
There was a memory fault on that node, so have resubmitted. However, they've been waiting since 11:30 today which is far slower than usual ...

**Comment by gcapes** [comment]
All step2 tasks have now completed. Step 3 still waiting in the queue.

**Comment by gcapes** [comment]
@RoryAtBar 
I have an error from the last script (step3), where it tries to write a list of InferenceData objects to netcdf. This function accepts InferenceData objects  - not lists. https://python.arviz.org/en/stable/api/generated/arviz.to_netcdf.html

```
Traceback (most recent call last):
  File "/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow/parallel_core_pymc/PYMC_GPflow_CSF3sampler_step3.py", line 24, in <module>
    az.to_netcdf(traces, f"{data_filename}.nc")
  File "/net/scratch2/mbexegc2/Abaqus_bayesian_matflow/test_venv/lib/python3.11/site-packages/arviz/data/io_netcdf.py", line 66, in to_netcdf
    inference_data = convert_to_inference_data(data, group=group, coords=coords, dims=dims)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/scratch2/mbexegc2/Abaqus_bayesian_matflow/test_venv/lib/python3.11/site-packages/arviz/data/converters.py", line 135, in convert_to_inference_data
    raise ValueError(
ValueError: Can only convert xarray dataarray, xarray dataset, dict, pytree, netcdf filename, numpy array, pystan fit, emcee fit, pyro mcmc fit, numpyro mcmc fit, cmdstan fit csv filename, cmdstanpy fit to InferenceData, not list
```
I'm not sure what you want to do about this - write  a series of netcdf files? Perhaps you could make the changes on the `gp_kernel_tester` branch?

**Comment by RoryAtBar** [comment]
Let me look, I have code that has successfully concatenated different netcdf files into one, and I was not expecting a problem…

From: Gerard Capes ***@***.***>
Date: Thursday, 26 September 2024 at 10:59
To: RoryAtBar/Abaqus_bayesian_matflow ***@***.***>
Cc: RoryAtBar ***@***.***>, Mention ***@***.***>
Subject: Re: [RoryAtBar/Abaqus_bayesian_matflow] Run updated scripts on CSF3 (Issue #20)

@RoryAtBar<https://github.com/RoryAtBar>
I have an error from the last script (step3), where it tries to write a list of InferenceData objects to netcdf. This function accepts InferenceData objects - not lists. https://python.arviz.org/en/stable/api/generated/arviz.to_netcdf.html

Traceback (most recent call last):

  File "/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow/parallel_core_pymc/PYMC_GPflow_CSF3sampler_step3.py", line 24, in <module>

    az.to_netcdf(traces, f"{data_filename}.nc")

  File "/net/scratch2/mbexegc2/Abaqus_bayesian_matflow/test_venv/lib/python3.11/site-packages/arviz/data/io_netcdf.py", line 66, in to_netcdf

    inference_data = convert_to_inference_data(data, group=group, coords=coords, dims=dims)

                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/net/scratch2/mbexegc2/Abaqus_bayesian_matflow/test_venv/lib/python3.11/site-packages/arviz/data/converters.py", line 135, in convert_to_inference_data

    raise ValueError(

ValueError: Can only convert xarray dataarray, xarray dataset, dict, pytree, netcdf filename, numpy array, pystan fit, emcee fit, pyro mcmc fit, numpyro mcmc fit, cmdstan fit csv filename, cmdstanpy fit to InferenceData, not list

I'm not sure what you want to do about this - write a series of netcdf files? Perhaps you could make the changes on the gp_kernel_tester branch?

**Comment by RoryAtBar** [comment]
My apologies Gerard, there should have been a line that concatenated the data from the netcdf files.

Should work now

From: Gerard Capes ***@***.***>
Date: Thursday, 26 September 2024 at 10:59
To: RoryAtBar/Abaqus_bayesian_matflow ***@***.***>
Cc: RoryAtBar ***@***.***>, Mention ***@***.***>
Subject: Re: [RoryAtBar/Abaqus_bayesian_matflow] Run updated scripts on CSF3 (Issue #20)

@RoryAtBar<https://github.com/RoryAtBar>
I have an error from the last script (step3), where it tries to write a list of InferenceData objects to netcdf. This function accepts InferenceData objects - not lists. https://python.arviz.org/en/stable/api/generated/arviz.to_netcdf.html

Traceback (most recent call last):

  File "/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow/parallel_core_pymc/PYMC_GPflow_CSF3sampler_step3.py", line 24, in <module>

    az.to_netcdf(traces, f"{data_filename}.nc")

  File "/net/scratch2/mbexegc2/Abaqus_bayesian_matflow/test_venv/lib/python3.11/site-packages/arviz/data/io_netcdf.py", line 66, in to_netcdf

    inference_data = convert_to_inference_data(data, group=group, coords=coords, dims=dims)

                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/net/scratch2/mbexegc2/Abaqus_bayesian_matflow/test_venv/lib/python3.11/site-packages/arviz/data/converters.py", line 135, in convert_to_inference_data

    raise ValueError(

ValueError: Can only convert xarray dataarray, xarray dataset, dict, pytree, netcdf filename, numpy array, pystan fit, emcee fit, pyro mcmc fit, numpyro mcmc fit, cmdstan fit csv filename, cmdstanpy fit to InferenceData, not list

I'm not sure what you want to do about this - write a series of netcdf files? Perhaps you could make the changes on the gp_kernel_tester branch?

**Comment by RoryAtBar** [comment]
FYI, the changes were committed to the gp_kernel_tester branch

**Comment by gcapes** [comment]
After another minor edit, the third script is now working!
