### ISSUE TITLE
Integrate functionality from `PYMC_GPflow_CSF3sampler_step1.sh`

### ISSUE THREAD

**Issue by gcapes** [RoryAtBar/Abaqus_bayesian_matflow#24]

**Comment by gcapes** [comment]
The `x` and `y` normalisers can't be passed as MatFlow parameters because they're not an object MatFlow can currently handle. The workaround was to save them as pickle files then load the files in the next task. However, when trying to load a file from a previous task, I keep getting file not found errors that I don't understand.
I'll ask Adam tomorrow

**Comment by RoryAtBar** [comment]
You know, saving the normalisers as pickle files was just a way of getting out of what felt like work.

In reality you could re-initialise them in the next step by passing an array with the same number of columns as the original data, and 2 rows containing the maximum and minimum of each column in the original data.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gcapes** [comment]
Ok, I've figured it out. My mock-up wasn't working because the tasks weren't executed sequentially because there was no explicit dependencies between them. Adding a 5s sleep fixed the error by giving the first task time to completed before the second task tried to load the file created in the first task.

Now to implement this in the real workflow!

**Comment by gcapes** [comment]
Well as it turns out, the x and y normaliser objects aren't used in step 1. They're loaded in by the original python script, but nothing is done with them. So we can leave this problem until later when I guess they're used in a later script :)

**Comment by gcapes** [comment]
I'm getting an error on CSF3 when I `import gpflow`. I thought that I've used the current venv to successfully run the original scripts, but maybe something has changed since then. I'm currently testing a new venv built from the `requirements.txt` file because I don't get this error by just importing gpflow locally (a more recent version of gpflow).

**Comment by gcapes** [comment]
Looks to work!

**Comment by gcapes** [comment]
Merged in d2f17520b6fa070e87ca15285d5cc3e4fc0dab8b #34
